# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='threadmodel',
            name='tpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_userinterface.TopicModel', verbose_name='topic'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='thr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_userinterface.ThreadModel', verbose_name='thread'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='tpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_userinterface.TopicModel', verbose_name='topic'),
        ),
    ]
