# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_userinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmodel',
            name='title',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
