# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-23 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_userinterface', '0002_threadmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pic_rel',
            field=models.ImageField(default=None, upload_to='', verbose_name='picture related'),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
